== The Speckled Egg

I am the speckled egg

the nest in the breeze

your feet on the ground

and the hole in your sleeve.

–Lady Velasquez

Once there was a house set upon the edge of a dark forest.
The man of the house was a widower.
He had two children, Marta, and Rico, who so loved one another that when they were apart, they could only be sad.

One day, their father told his cook and laborer of pressing business he had abroad.
He said he must pass through the dark forest, but he promised his return before the full moon.

The full moon came and went and still Marta and Rico’s father did not return.
To the laborer, the cook served up a cup of cheer in the kitchen.
She said the master of the house must surely be dead in the forest, killed by bandits.
She was raised among them and knew they would as soon waylay a stranger as say “good day.” The Cook hinted the house was as good as theirs if they could only get rid of the children.

“Tomorrow,” said she, “I’ll put a large pot on to boil for Rico.
And where he goes Marta will soon follow.”

The children were fond of playing hiding games, and overhearing these plans from behind the pantry door, they shuddered.

Marta whispered “But Rico, instead of this, tomorrow we must rise earlier than misfortune.
You and I will dress and go far away.”

The next day the children did as they planned.
In the kitchen when the kettle began to boil, the cook said it was time to fetch sleepy Rico.
Entering their room, they immediately saw that both children were gone.
She sent the laborer to find them.
But on the edge of the forest, the children saw him coming from afar.

Marta said to Rico “Say quick.
We belong together.”

“Forever and ever more,” said Rico.

“In this tree, you must become a nest — and look I will be the egg.”

When the laborer came to the forest, he found nothing there of interest but a swaying nest with one lovely egg.
“There is nothing to do here,” he said and went back to tell the cook.

The cook scolded him.
“You simpleton you should have torn the nest down, taken the egg and brought it back.
Go and do it at once.”

He went out a second time, but again the children saw him coming.

“Rico say quickly.
We belong together,” said Marta.

“Forever and ever more,” said Rico.

“Then you must become a church — and look I will be the candle.”

So when the laborer came, he found nothing but a church with one pale candle flickering inside.

He said, “What can I do here? Let us go.”

Upon returning to the house, he explained all he had found.

“You fool! Why did you not pull the church to pieces and bring the candle home with you?”

Now, the cook got herself up and went.
The children saw them coming from afar, this time, the cook with the laborer in tow.

“Rico say quickly.
We belong together,” said the sister.

“Forever and ever more,” said her brother.

“Be a fishpond — and look I will be what I must.”

The two wicked servants came up then.
When the cook saw the pond full of golden fish, she suspected some ruse.
One especially beautiful carp swam close to the surface — almost close enough for her to grab, if the laborer would only steady her balance.
But a white goose came up from behind and bit the man’s legs, honking and beating its wings upon him like a great storm.

He let go, and the cook fell head first into the water.
Taking to his heels while she splashed away, neither of them were ever to be seen again.

Rico and Marta went home.
There they found their father returned from his travels and weeping at the table.
He cried bitterly in his arms for the return of his lost children.
With a shout, they were joyously reunited — and if they have not yet died happy, they are living still.

