== The Speckled Egg
.quote
I am the speckled egg, + 
the nest in the breeze, + 
your feet on the ground, and + 
the hole in your sleeve. + 
		-– Lady Villareal.

Once there was a house upon the edge of a very dark forest.
In this house lived two children, Marta and Rico.
They so loved one another that whenever they were apart, they could only be sad.

One day their father told Marta and Rico he must leave for pressing business abroad.
He entrusted their care to the cook and laborer, promising to return before the next full moon.
And so he passed into the dark forest, waving goodbye before slipping out of sight.

Days and nights passed.
The full moon came and went.
Still Marta and Rico’s father did not return.

One night, after the children had gone to bed, the cook raised a toast to the laborer.
She said the master of the house must surely be dead.
The dark forest was full of bandits; she knew well.
And these bandits would rob a man and slit his throat just as a matter of business." She added that the house would be good as theirs if they could only get rid of the children.

"`Tomorrow,`" said the cook, "`we will put a large pot on to boil for Rico.
And where he goes, Marta will soon follow.`"

The two children were fond of hiding games.
With their ears to the kitchen door, hearing the wicked plan, their mouths fell open.
Quietly they slipped away.
Marta whispered, "`But Rico, instead of this, tomorrow we will rise earlier than does our misfortune.`"

The next day when the kitchen kettle came to a rolling boil, the cook said it was time to fetch sleepy Rico.
On tip-toes, they entered the children’s room.
The cook held the candle high while the laborer lifted back the covers.
With a start, they found only a bundle of clothes in two neat piles.

"`Gone! The little brutes, the little thieves.`" cried the cook.
"`Go find them at once and bring them back.`"

In the forest the children spied the laborer some distance behind and tracking their trail.

Rico cried.
"`What shall we do?`"

Marta said to Rico, "`Say quick; we belong together.`"

"`Forever and evermore,`" said Rico.

"`Then, in this tree, you must become a nest – and look, I will be the egg.`"

The laborer came up to the tree, but he found nothing there of interest, only a swaying nest with one lovely egg.
"`I have surely lost the trail,`" he said and went back to tell the cook.

The cook scolded him.
"`Bah, Simpleton! You should have torn the nest down, taken the egg and brought it back.
Go do it at once.`"

The man went out a second time, but again the children saw him coming from afar.

"`Rico say quick, we belong together,`" said Marta.

"`Forever and evermore,`" said Rico.

"`Then, you must become a church – and look, I will be the candle.`"

So, when the laborer came to a clearing, he found nothing but a church with one bright candle flickering upon the altar.
He said, "`There are no children here.
Again, the trail has gone cold.`"

Upon returning to the house, he explained all he had found.

"`You fool! Why did you not pull the church to pieces and bring the candle home with you?`"

Now, the cook got herself up and went out together in pursuit of the children.
But Marta and Rico expected trouble yet and saw them coming.

"`Rico say quick, we belong together,`" said Marta.

"`Forever and evermore,`" said her brother.

"`Then be a fishpond and look, I will be what I must.`"

The two wicked servants came up then.
When the cook saw a pond full of golden fish in the dark forest, she suspected some ruse.
One magnificent pink and white carp swam close to the surface – almost close enough for her to grab.
She ordered the laborer to help steady her balance.
All of a sudden, a white goose came up from behind and bit the laborer’s legs, honking and beating wings upon him wildly.

The man let go, wherein the cook fell headfirst into the water.
The laborer took to his heels while the cook splashed away.
Neither were ever seen again.

At last, Rico and Marta were free to go home.
Once there, they found father returned and weeping at the table.
He cried bitterly in his arms for the lives of his lost children.

With a shout they were joyously reunited.
And if they have not yet died happily, they are living still.

END
